# Generated by Django 4.1.7 on 2023-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="logo",
            field=models.ImageField(default="default_logo.png", upload_to="images/"),
        ),
    ]
