# Generated by Django 4.1.7 on 2023-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="NGO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Ngo Name")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Ngo location"),
                ),
                ("email", models.CharField(max_length=50)),
                ("contactno", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("website", models.CharField(max_length=500)),
            ],
        ),
    ]
